image: node:10.6.0

pipelines:
  default:
    - step:
        name: Build
        script:
          - yarn
          - yarn run build
    - step:
        name: Publish
        trigger: manual
        deployment: production
        script:
          - yarn
          - yarn run build
          - yarn config set version-git-message "Upgrade to v%s [skip ci]"
          - yarn version --minor
          - git push && git push --tags
          - pipe: atlassian/npm-publish:0.2.0
            variables:
              NPM_TOKEN: $NPM_TOKEN
              EXTRA_ARGS: --access=public
